// <auto-generated />
using System;
using LookAtMe.Web.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LookAtMe.Web.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190523002018_Changed_Database")]
    partial class Changed_Database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LookAtMe.Web.API.Domain.Model.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Capturado");

                    b.Property<DateTime>("DataHoraRegistro");

                    b.Property<string>("Estado")
                        .IsRequired();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<int>("NumeroOnibus");

                    b.Property<int>("SuspeitoId");

                    b.Property<string>("UrlFoto")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Alerta");
                });
#pragma warning restore 612, 618
        }
    }
}
