// <auto-generated />
using System;
using LookAtMe.Web.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LookAtMe.Web.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LookAtMe.Web.API.Domain.Model.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Capturado");

                    b.Property<DateTime>("DataOcorrencia");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<TimeSpan>("HoraOcorrencia");

                    b.Property<int>("LinhaTranscol");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SuspeitoId");

                    b.HasKey("Id");

                    b.HasIndex("SuspeitoId");

                    b.ToTable("Alerta");
                });

            modelBuilder.Entity("LookAtMe.Web.API.Domain.Model.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataRegistro");

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<TimeSpan>("HoraRegistro");

                    b.Property<int>("SuspeitoId");

                    b.HasKey("Id");

                    b.HasIndex("SuspeitoId");

                    b.ToTable("Ocorrencia");
                });

            modelBuilder.Entity("LookAtMe.Web.API.Domain.Model.Suspeito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Foto")
                        .IsRequired();

                    b.Property<int>("Idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Suspeito");
                });

            modelBuilder.Entity("LookAtMe.Web.API.Domain.Model.Alerta", b =>
                {
                    b.HasOne("LookAtMe.Web.API.Domain.Model.Suspeito", "Suspeito")
                        .WithMany()
                        .HasForeignKey("SuspeitoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LookAtMe.Web.API.Domain.Model.Ocorrencia", b =>
                {
                    b.HasOne("LookAtMe.Web.API.Domain.Model.Suspeito", "Suspeito")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("SuspeitoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
